### ISSUE TITLE
How to fail based on a condition?

### ISSUE THREAD

**Issue by mrclay** [RxNT/json-rules-engine-simplified#21]
I'm creating a date range, so the end has to be later than the start. I can create an event based on conditions referencing the fields, but I basically need a "failValidation" event. Or I suppose an event that adds a minimum on the end date. Any ideas here?

**Comment by mavarazy** [comment]
You can trigger negative event, on value out of range, for example:
    {
        type: "INVALID_DATE",
        props: {
            message: "Invalid date specified for field A"
        }
    }

**Comment by mavarazy** [comment]
@mrclay happy to accept as a new feature request 👍 I'll close this for now.
