### ISSUE TITLE
Can conditions run on individual objects in an array?

### ISSUE THREAD

**Issue by mrclay** [RxNT/json-rules-engine-simplified#22]
We have an array of objects, and need conditions to apply based on fields in *the same array element*. Something like:
```js
{
  conditions: {
    'arr[x].foo': { equal: true }},
  },
  event: {
    type: 'remove',
    params: { field: 'arr[x].bar' }
  }
};
```

**Comment by mrclay** [comment]
I think we'll have to process rules separately for each object in formData. We're already using a separate Form element to handle conditionals within the array object.

**Comment by mavarazy** [comment]
@mrclay for internal selection _selectn_ library is used, so as long is you have a specific index in the array, there is no problem with rulesEngine, but I suspect there will be a problem with react-jsonschema-form-conditionals project, I'll check. Refer to the test that I submitted.

**Comment by mavarazy** [comment]
For this project it can

**Comment by mavarazy** [comment]
Here is a test for removing element from an array in conditionals project
https://github.com/RxNT/react-jsonschema-form-conditionals/commit/4667979a10b641a27be68fa5a15eea73860a3154
