### ISSUE TITLE
create-react-app build process broken

### ISSUE THREAD

**Issue by czycha** [RxNT/json-rules-engine-simplified#23]
_[See Predicate issue #10](https://github.com/landau/predicate/issues/10)_

I'm using json-rules-engine-simplified paired with react-jsonschema-form-conditionals for a web app that I'm building using create-react-app. 

The form works perfectly well when in development mode. However, I'm unable to build the app for deployment because [create-react-app does not minify ES6 features](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). This issue affects this module because it depends on [Predicate](https://github.com/landau/predicate), which uses ES6. 

I spoke with the maintainer of that project, and they are hoping to stick with ES6 as their entry point. So I'm posting here to suggest importing `predicate/dist/predicate` instead of just `predicate`. This file is just Predicate transpiled to ES5.

The affected files are:
- src/checkField.js
- src/validation.js

**Comment by donalmurtagh** [comment]
@mavarazy Could you please release version 0.1.17?
