### ISSUE TITLE
Usage in browser?

### ISSUE THREAD

**Issue by htammen** [RxNT/json-rules-engine-simplified#25]
I would like to use your library in a browser. Is this possible?
I tried to browserify without success. Any suggestions?

**Comment by htammen** [comment]
Got it with browserify and babelify. So I can use it in a browser now.

**Comment by mavarazy** [comment]
@htammen that is great.
Can you add description of how to do it here or in the README

**Comment by htammen** [comment]
@mavarazy I've created a demo app and published it [here](https://github.com/htammen/ui5-json-rules-engine). In my readme.md I describe the process briefly under Technical implementation. Want to go into more detail soon. Stay tuned and don't hesitate to remind me if it takes too long.
