### ISSUE TITLE
Update the documentation for using custom predicates

### ISSUE THREAD

**Issue by Steffan-Ennis** [RxNT/json-rules-engine-simplified#28]
- checkField.js has the distribution version of predicate as a dependency
- The documentation says to import the non distribution version, when currying in extra predicates

**Comment by mavarazy** [comment]
@Steffan-Ennis can you provide an example or reference, I don't see it in the documentation.

I'm sorry if it's causing problems, just want to make sure it won't break something in the future, since this change was made in order to help someone else using the library.

**Comment by yowzadave** [comment]
I'm unable to add a custom predicate—I'm assuming that this is the issue affecting me as well.

**Comment by Steffan-Ennis** [comment]
@mavarazy Sure

It's under the Extending available predicates heading in the readme

the predicate import statement should be this `import predicate from 'predicate/dist/predicate'`

**Comment by mavarazy** [comment]
@Steffan-Ennis @yowzadave got it, removed dist dependency and released minor version - 0.1.17
