### ISSUE TITLE
Fail to handle string[]

### ISSUE THREAD

**Issue by Steffan-Ennis** [RxNT/json-rules-engine-simplified#5]
I'm not sure if this is intentional behaviour. If it is it would be a good feature to be able to compare arrays and not just their items

Found a bad condition check on line 7  of conditionsMeet.js
 line 7-8
`if (!isObject(conditions) || !isObject(formData)) {
    toError(`Rule ${conditions} with ${formData} can't be processed`);
  }` 

line 21
` return refVal.some(val => conditionsMeet(refCondition, val));`

can call with bad arguments

Example condition, targets is a string[]
`"conditions": {
      "targets": "_empty"
    }`

<img width="823" alt="screen shot 2017-07-26 at 12 54 39 pm" src="https://user-images.githubusercontent.com/16796843/28603366-be6de860-7202-11e7-9d51-f0493ce51791.png">
<img width="805" alt="screen shot 2017-07-26 at 12 55 19 pm" src="https://user-images.githubusercontent.com/16796843/28603365-be6d8708-7202-11e7-97dd-19ecc0ca700d.png">

**Comment by Steffan-Ennis** [comment]
ps I really like the library. Good work

**Comment by mavarazy** [comment]
Thanks, a lot, sorry for getting back late to this.
Can you clarify something
1. Condition
`"conditions": { "targets": "_empty" }`
`_empty` is not part of [predicate](http://landau.github.io/predicate) js library, that is used.
It should display appropriate error when you try to use it this way

Try with this one
`"conditions": { "targets": "empty" }` 

2. By referencing line 7 and related checks, do you mean you want to feed something other, than object to the rules engine?

I've opened an issue - https://github.com/RxNT/json-rules-engine-simplified/issues/7, which should allow you to specify any conditional logic you want.

**Comment by Steffan-Ennis** [comment]
Hey, thanks for getting back to me. 

I like your solution for extending the predicate logic. I took a very similar approach by extending the import predicate object. 

I referenced line 23 because it would be nice to have the empty predicate ran against the array and its elements. 

something like this.
`if(Array.isArray(refVal)) {
  return refVal.some(val => conditionsMeet(refCondition, val)) || checkField(refVal, refCondition) 
}
`
 and in checkField line 9
` return fieldVal.some(val => checkField(val, rule)) || predicate[rule](fieldVal) `

The feature could be very useful associating rules against json-schema-form arrays. We have a use case for hiding an entire section of the form until one element has been added to the array.

**Comment by mavarazy** [comment]
@Steffan-Ennis Can you give me an example? So I would see how to better address this?

**Comment by mavarazy** [comment]
@Steffan-Ennis merged your request

**Comment by Steffan-Ennis** [comment]
Awesome, thanks.

**Comment by mavarazy** [comment]
@Steffan-Ennis I've updated your fix, should still work
